name: Edit File on Issue Title Change

on:
  issues:
    types: [opened, edited]

jobs:
  edit_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get issue body
        id: get_title
        run: echo "::set-output name=title::${{ github.event.issue.body }}"

      - name: Edit save.txt
        run: |
          echo "${{ steps.get_title.outputs.title }}" > save.txt

      - name: Commit + push
        run: |
          git config --local user.email "organiserapptasks@gmail.com"
          git config --local user.name "organiserapptasks"
          git add edited_file.txt
          git commit -m "Update file based on issue title"
          git push https://github.com/${{ github.repository }} HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.AUTH_TOKEN }}
